### ISSUE TITLE
I want to know how to create mod lang

### ISSUE THREAD

**Issue by AomTheera** [BrandenEK/Blasphemous-Andalusian#2]
Hi! I'm blasphemous fan from Thailand and i want to show Thailand gamer to know about blasphemous story so I wanna create mod lang I spend many time for learning about lang mod and now I found you. and you can !!! so can u teach me how? pls

**Comment by BrandenEK** [comment]
Certainly.  All you would have to do is make a file that contains all of the Thai translations.  The Andalusian one is [right here](https://github.com/BrandenEK/Blasphemous-Andalusian/blob/main/resources/data/Andalusian/language.txt), and the in-game examples can be found [here](https://github.com/BrandenEK/Blasphemous-Andalusian/tree/main/Exported%20Languages).  Feel free to contact me on discord if you have any more questions

#damocles03

**Comment by AomTheera** [comment]
ok I have some questions i tried to change some words in language.txt in The Andalusian mod for make sure it can be
but when I try it I don't see Thai text why?
![image](https://github.com/BrandenEK/Blasphemous-Andalusian/assets/57719353/d7f0e92f-aa50-4fcc-a129-7c9b3a3caa91)

**Comment by BrandenEK** [comment]
You changed the part that displays text on the left, so it worked. The actual language name is handled somewhere else.

**Comment by AomTheera** [comment]
ok if u focus it i change it to "ทดสอบภาษาไทย (Text thai lang)" but in game is show only "(Text thai lang)" the "ทดสอบภาษาไทย" are missing why?

**Comment by AomTheera** [comment]
i add friend you in discord pls accept me i need u help 🥺🥺

**Comment by AomTheera** [comment]
my id #stealgirlfriend.666
